In [1]:
import gym
from gym.envs.registration import register
from baselines import deepq
import environment

/Users/pradeepkadubandi/.local/share/virtualenvs/Agroecology-Agent-y-4emjLa/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/pradeepkadubandi/.local/share/virtualenvs/Agroecology-Agent-y-4emjLa/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/pradeepkadubandi/.local/share/virtualenvs/Agroecology-Agent-y-4emjLa/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (

In [2]:
env_id = 'AgroEcology-v0'
register(
      id=env_id,
      entry_point='environment:EnvironmentV2',
  )

In [3]:
def callback(lcl, _glb):
    return False
      # stop training if reward exceeds 199
#     is_solved = lcl['t'] > 100 and sum(lcl['episode_rewards'][-101:-1]) / 100 >= 199
#     return is_solved

In [4]:
env = gym.make(env_id, field_size=10)

In [5]:
print ("field_size = {}".format(env.field_size))
env.render('human')

field_size = 10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
act = deepq.learn(
    env,
    network='mlp',
    lr=1e-3,
    total_timesteps=100000,
    buffer_size=5000,
    exploration_fraction=0.1,
    exploration_final_eps=0.02,
    print_freq=25
)







Instructions for updating:
Use `tf.cast` instead.
Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/Users/pradeepkadubandi/.local/share/virtualenvs/Agroecology-Agent-y-4emjLa/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/pradeepkadubandi/.local/share/virtualenvs/Agroecology-Agent-y-4emjLa/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Logging to /var/folders/02/lgy5bs_d0m97qncpm9x8lk3r0000gp/T/openai-2019-09-14-15-34-17-653164
--------------------------------------
| % time spent exploring  | 76       |
| episodes                | 25       |
| mean 100 episode reward | 489      |
| steps                   | 2.4e+03  |
--------------------------------------
--------------------------------------
| % time spent exploring  | 51       |
| episodes                | 50       |
| mean 100 episode reward | 491      |
| steps                   | 4.9e+03  |
--------------------------------------
--------------------------------------
| % time spent exploring  | 27       |
| episodes                | 75       |
| mean 100 episode reward | 472      |
| steps                   | 7.4e+03  |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 100      |
| mean 100 episode reward | 426      |
| steps                   | 9.9e+03  |
---------

--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 875      |
| mean 100 episode reward | 684      |
| steps                   | 8.74e+04 |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 900      |
| mean 100 episode reward | 660      |
| steps                   | 8.99e+04 |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 925      |
| mean 100 episode reward | 582      |
| steps                   | 9.24e+04 |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 950      |
| mean 100 episode reward | 508      |
| steps                   | 9.49e+04 |
--------------------------------------
--------------------------------------
| % time spent exploring 

In [7]:
for i in range(5):
    obs, done = env.reset(), False
    episode_rew = 0
    while not done:
        obs, rew, done, _ = env.step(act(obs[None])[0])
        episode_rew += rew
    print ("Environment at end of episode:")
    env.render('human')
    print("Episode reward", episode_rew)

Environment at end of episode:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Episode reward 20.0
Environment at end of episode:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Episode reward 0.0
Environment at end of episode:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 